### ISSUE TITLE
Bignum stacktrace

### ISSUE THREAD

**Issue by dave7373** [campanja/fluent-output-router#3]
We get a lot of these stacktraces sometimes:

```ruby
2013-08-30 10:04:14 +0000 [warn]: emit transaction failed error_class=TypeError error=#<TypeError: nil can't be coerced into Bignum>
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/output.rb:500:in `/'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/output.rb:500:in `block in emit'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/event.rb:52:in `call'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/event.rb:52:in `each'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/output.rb:499:in `emit'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-output-router-0.9.3/lib/fluent/plugin/out_router.rb:68:in `emit'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/match.rb:38:in `emit'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/engine.rb:134:in `emit_stream'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/engine.rb:115:in `emit'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:121:in `block in Log'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:116:in `each'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:116:in `Log'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/thrift/scribe.rb:38:in `process_Log'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/processor.rb:29:in `process'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:295:in `block in run'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:281:in `loop'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:281:in `run'
2013-08-30 10:04:14 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:274:in `block in spawn'
```

The root case seems to be this:

```
2013-08-30 13:43:04 +0000 [info]: out_router: Starting a new output of type s3 for key 1369
2013-08-30 14:02:29 +0000 [info]: out_router: Stopping output of type s3 for key 1369 due to inactivity (no data comming in)
2013-08-30 14:58:47 +0000 [info]: out_router: Starting a new output of type s3 for key 1369
2013-08-30 14:58:47 +0000 [warn]: emit transaction failed error_class=Fluent::ConfigError error=#<Fluent::ConfigError: Other 's3' plugin already use same buffer_path: type = s3, buffer_path = /mnt/eph
emeral0/td-agent/router.tag.1369/s3>
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/plugin/buf_file.rb:91:in `configure'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/output.rb:172:in `configure'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/output.rb:451:in `configure'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/mixin.rb:186:in `configure'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/mixin.rb:135:in `configure'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-mixin-config-placeholders-0.2.3/lib/fluent/mixin/config_placeholders.rb:93:in `configure'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-s3-0.3.4/lib/fluent/plugin/out_s3.rb:47:in `configure'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-output-router-0.9.3/lib/fluent/plugin/out_router.rb:89:in `block in start_output'
2013-08-30 14:58:47 +0000 [warn]: <internal:prelude>:10:in `synchronize'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-output-router-0.9.3/lib/fluent/plugin/out_router.rb:80:in `start_output'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-output-router-0.9.3/lib/fluent/plugin/out_router.rb:66:in `emit'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/match.rb:36:in `emit'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/engine.rb:138:in `emit_stream'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.38/lib/fluent/engine.rb:118:in `emit'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:121:in `block in Log'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:116:in `each'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:116:in `Log'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/thrift/scribe.rb:38:in `process_Log'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/processor.rb:29:in `process'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:295:in `block in run'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:281:in `loop'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:281:in `run'
2013-08-30 14:58:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/thrift-0.8.0/lib/thrift/server/nonblocking_server.rb:274:in `block in spawn'
```

**Comment by dave7373** [comment]
Keeping the workaround so I will close this issue
