### ISSUE TITLE
Thread cleanup problem

### ISSUE THREAD

**Issue by dave7373** [campanja/fluent-output-router#4]
It looks like the s3 plugins are shut down, but their threads keeps on living.
This has to be investigated.

```ruby
2013-09-01 17:29:47 +0000 [warn]: emit transaction failed error_class=ThreadError error=#<ThreadError: can't create Thread (11)>
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/timeout.rb:59:in `start'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/timeout.rb:59:in `timeout'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/timeout.rb:99:in `timeout'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/net/http.rb:762:in `connect'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/net/http.rb:755:in `do_start'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/1.9.1/net/http.rb:750:in `start'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/net/http/connection_pool/session.rb:118:in `start'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/net/http/connection_pool.rb:208:in `_create_session'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/net/http/connection_pool.rb:193:in `session_for'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/net/http/connection_pool.rb:171:in `request'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/net/http/connection_pool/connection.rb:173:in `request'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/http/net_http_handler.rb:66:in `handle'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:230:in `block in make_sync_request'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:266:in `retry_server_errors'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:226:in `make_sync_request'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:457:in `block (2 levels) in client_request'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:340:in `log_client_request'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:426:in `block in client_request'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:322:in `return_or_raise'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/core/client.rb:425:in `client_request'
2013-09-01 17:29:47 +0000 [warn]: (eval):3:in `get_bucket_versioning'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/s3/bucket.rb:455:in `versioning_state'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/s3/bucket.rb:443:in `versioning_enabled?'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/aws-sdk-1.8.3.1/lib/aws/s3/bucket.rb:506:in `exists?'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-s3-0.3.4/lib/fluent/plugin/out_s3.rb:176:in `ensure_bucket'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-s3-0.3.4/lib/fluent/plugin/out_s3.rb:107:in `start'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-output-router-0.9.3/lib/fluent/plugin/out_router.rb:90:in `block in start_output'
2013-09-01 17:29:47 +0000 [warn]: <internal:prelude>:10:in `synchronize'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-output-router-0.9.3/lib/fluent/plugin/out_router.rb:80:in `start_output'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-output-router-0.9.3/lib/fluent/plugin/out_router.rb:66:in `emit'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/match.rb:38:in `emit'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/engine.rb:134:in `emit_stream'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluentd-0.10.36/lib/fluent/engine.rb:115:in `emit'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:121:in `block in Log'
2013-09-01 17:29:47 +0000 [warn]: /usr/lib/fluent/ruby/lib/ruby/gems/1.9.1/gems/fluent-plugin-scribe-0.10.10/lib/fluent/plugin/in_scribe.rb:116:in `each'
```

**Comment by dave7373** [comment]
Keeping the workaround so I will close this issue
